name: Go

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Pack Linux
      if: startsWith(matrix.os,'ubuntu')
      run: |
        go build -o slf
        tar cfvz slf-linux-amd64.tar.gz slf

    - name: Pack Windows
      if: startsWith(matrix.os,'windows')
      run: |
        go build -o slf.exe
        7z a slf-windows-amd64.zip slf.exe

    - name: Pack macOS
      if: startsWith(matrix.os,'macOS')
      run: |
        go build -o slf
        tar cfvz slf-darwin-amd64.tar.gz slf

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: slf-*
        retention-days: 1

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download artifcat
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
